export const cases = [
  {
    id: 'normal-title',
    category: 'normal',
    kind: 'html-semantic',
    selector: '#page-title',
    tag: 'h1',
    expectedText: 'Museum walk',
    expectedAttributes: [],
    feedback: 'The page title needs an h1.',
  },
  {
    id: 'normal-section',
    category: 'normal',
    kind: 'html-semantic',
    selector: '#start-heading',
    tag: 'h2',
    expectedText: 'Start here',
    expectedAttributes: [],
    feedback: 'Use h2 for the major section.',
  },
  {
    id: 'boundary-subsection',
    category: 'boundary',
    kind: 'html-semantic',
    selector: '#times-heading',
    tag: 'h3',
    expectedText: 'Opening times',
    expectedAttributes: [],
    feedback: 'Use h3 for this subsection.',
  },
];
